# Generated by Django 4.2.1 on 2023-05-12 08:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'BlogCategory',
                'verbose_name_plural': 'BlogCategories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('small_description', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('small_description', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
