# Generated by Django 4.2.1 on 2023-05-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_device_type_alter_client_repair_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='small_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='device_type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablets', 'Tablets')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='repair_type',
            field=models.CharField(choices=[('Screen damage', 'Screen damage')], max_length=100),
        ),
    ]
